# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/dht.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/dht.proto\x12\x03\x44HT\x1a\x1bgoogle/protobuf/empty.proto\",\n\x04Join\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x03\"o\n\x06JoinOk\x12\x0f\n\x07next_id\x18\x01 \x01(\x03\x12\x0f\n\x07next_ip\x18\x02 \x01(\t\x12\x11\n\tnext_port\x18\x03 \x01(\t\x12\x0e\n\x06pre_id\x18\x04 \x01(\x03\x12\x0e\n\x06pre_ip\x18\x05 \x01(\t\x12\x10\n\x08pre_port\x18\x06 \x01(\t\" \n\x04\x46ile\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\xc9\x02\n\x03\x44HT\x12\x1f\n\x05hello\x12\t.DHT.Join\x1a\t.DHT.Join\"\x00\x12\x32\n\x0btry_to_join\x12\t.DHT.Join\x1a\x16.google.protobuf.Empty\"\x00\x12\x36\n\rjoin_response\x12\x0b.DHT.JoinOk\x1a\x16.google.protobuf.Empty\"\x00\x12>\n\x17uptade_next_node_params\x12\t.DHT.Join\x1a\x16.google.protobuf.Empty\"\x00\x12\x42\n\x1buptade_previuos_node_params\x12\t.DHT.Join\x1a\x16.google.protobuf.Empty\"\x00\x12\x31\n\nstore_file\x12\t.DHT.File\x1a\x16.google.protobuf.Empty\"\x00\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.dht_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_JOIN']._serialized_start=54
  _globals['_JOIN']._serialized_end=98
  _globals['_JOINOK']._serialized_start=100
  _globals['_JOINOK']._serialized_end=211
  _globals['_FILE']._serialized_start=213
  _globals['_FILE']._serialized_end=245
  _globals['_DHT']._serialized_start=248
  _globals['_DHT']._serialized_end=577
# @@protoc_insertion_point(module_scope)
